# Configurações gerais para o projeto
app_name: playlist-recommender
namespace: gabrielafreitas

# Configurações do ML Container
ml_container:
  image: quay.io/gmiserani/playlists-recommender-system-ml:0.5
  dataset: ds2.csv
  dataset_base_path: /app/datasets/spotify/
  output_path: /model/recommendation_rules.pkl

# Configurações do Frontend Container
frontend_container:
  image: quay.io/gmiserani/playlists-recommender-system-app:0.6
  model_path: /model/recommendation_rules.pkl
