apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gabrielafreitas
  labels:
    app: frontend-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabrielafreitas-frontend-container
  template:
    metadata:
      labels:
        app: gabrielafreitas-frontend-container
    spec:
      containers:
      - name: frontend-container
        image: quay.io/gmiserani/playlists-recommender-system-app:0.4
        ports:
        - containerPort: 52021
        volumeMounts:
        - name: persistent-storage
          mountPath: /model
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: playlist-recommender-pvc-gabrielafreitas
