apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job-ds8
  namespace: gabrielafreitas
spec:
  template:
    metadata:
      labels:
        app: gabrielafreitas-ml-container
    spec:
      containers:
      - name: ml-container
        image: quay.io/gmiserani/playlists-recommender-system-ml:0.6
        env:
        - name: DATASET_NAME
          value: 2023_spotify_ds2.csv
        - name: DATASET_BASE_PATH
          value: /app/datasets/spotify/ 
        - name: OUTPUT_PATH
          value: /model/recommendation_rules.pkl
        volumeMounts:
        - name: datasets-volume
          mountPath: /app/datasets
        - name: persistent-storage
          mountPath: /model
      volumes:
      - name: datasets-volume
        hostPath:
          path: /home/datasets
          type: Directory
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: playlist-recommender-pvc-gabrielafreitas
      restartPolicy: Never
