apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: gabrielafreitas-frontend-container
  ports:
    - protocol: TCP
      port: 52021
      targetPort: 52021